[package]
name = "json_parser"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "run_parser"
path = "src/main.rs"

[lib]
name = "json_parser"
path = "src/lib.rs"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui-modal = "0.4.0"
egui_extras = "0.28.1"
rfd = "0.14.1"
